baseURL = "https://www.williamleme.com/"
languageCode = "en-us"
title = "William Leme"
theme = "hugo-theme-mini-master"
paginate = 10

copyright = "© William Leme"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = false

googleAnalytics = "UA-50971964-4"
disqusShortname = ""

summaryLength = 20

[params]
	subtitle = "Software Engineer"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "light" # "dark", "auto", "light"
	customCSS = "css/custom-vs1.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.
	customJS = ["js/custom-vs1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

#[[menu.main]]
#name = "All posts"
#url = "/posts"
#weight = 2

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 500

[[menu.main]]
name = "Sample Apps"
weight = 400
identifier = "apps"
url = "/wllapps/"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/wleme"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/williamleme/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://www.twitter.com/wleme/"

#[[params.social]]
#name = "RSS"
#icon = "rss"
#url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackfriday]
    hrefTargetBlank = true